In [1]:
import pandas as pd

In [2]:
result = pd.read_csv("../output/report/result_TRANSFER_logreg.csv")
result

     class_weight  precision    recall  f1-score  false_positive_rate
0               1   0.952199  0.811075  0.875989             0.000315
1               2   0.939929  0.866450  0.901695             0.000429
2               3   0.931624  0.887622  0.909091             0.000504
3               4   0.888399  0.985342  0.934363             0.000958
4               5   0.879710  0.988599  0.930982             0.001046
..            ...        ...       ...       ...                  ...
507           508   0.105681  0.996743  0.191101             0.065290
508           509   0.105481  0.996743  0.190773             0.065429
509           510   0.105336  0.996743  0.190535             0.065530
510           511   0.105137  0.996743  0.190210             0.065668
511           512   0.105028  0.996743  0.190033             0.065744

[512 rows x 5 columns]